### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by FahmiAyil** [mololab/json-translator#13]
Hi, I have some issue using jsontt CLI, i have json with 5k char, and i want to translate into all language in this library (but for the screenshoot i only translate into afrikaans) , but it says Too Many Requests

how to solve this problem?
![Screenshot from 2022-11-07 19-28-36](https://user-images.githubusercontent.com/12084891/200310987-2c20a05f-fe37-4b51-998c-7df83fb6607f.png)

**Comment by ParvinEyvazov** [comment]
Hello, thank you for the report.

Can you please try another language translation option? (Libre Translate or Argos Translate)

**Comment by ParvinEyvazov** [comment]
Hello @FahmiAyil , thank you for the report.

Can you please try another language translation option? (Libre Translate or Argos Translate)

**Comment by FahmiAyil** [comment]
i am using version 1.3.0

if im using another option its working perfect, but honestly my project need google translate as translator, cause it support so many languages

**Comment by ParvinEyvazov** [comment]
I got it. Unfortunately, Google Translate API tries to block suspicious requests, it is hard to run away from it. I will try to add a new feature that will divide big strings (like 5k char) into some pieces, translate them and merge them. But I don't think I can do it in a short period of time. Maybe for now:

You can divide this 5k char string into more parts, translate them and merge them manually.

**Comment by FahmiAyil** [comment]
okay, thankyou for your respond

**Comment by ParvinEyvazov** [comment]
@FahmiAyil I did a couple of improvements on preventing this error. Can you please try again?
