### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Kamikoto-mono** [mololab/json-translator#15]
Is it possible to add automatically ignoring null value?

**Comment by ParvinEyvazov** [comment]
Hey hello @Kamikoto-mono 

Do you mean like this? :

```
{
  "name": null
}
```

or 

```
{
  "name": undefined
}
```

**Comment by Kamikoto-mono** [comment]
{
  "name": null
}

**Comment by ParvinEyvazov** [comment]
Hi @Kamikoto-mono 

With version v1.4.2 and up, now it ignores `null` values 🌟. 

Thank you for your feedback & suggestion.
