### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by emres8** [mololab/json-translator#16]
Hi, firstly great work. I am trying to use sample usage 5 (multiple language) on js for a very simple short json. It gives me an error:

> Translation error: TypeError: Cannot read properties of undefined (reading 'length')  at _callee$ (translate/node_modules/@parvineyvazov/json-translator/dist/json-translator.cjs.development.js:513:36).

 I fixed the issue by adding a ? to the given line 
` if (!(global.proxyList?.length > 0 && global.proxyIndex != -1)) {`. 
But  couldn't understand why global.proxylist is undefined. Any recommendations on how to proceed? Thanks

**Comment by ParvinEyvazov** [comment]
Hi @emres8 , Thank you for your comment.

First I would like to ask, are you using a proxy or the default one (without any proxy)?

**Comment by emres8** [comment]
default one

**Comment by emres8** [comment]
I am using the default one (without any proxy), should I use one?

**Comment by ParvinEyvazov** [comment]
Hi again @emres8 , I just released a new patch version v1.4.1 to fix this issue. Can you please try now?
