### ISSUE TITLE
Multiple errors when trying to translate with libretranslate

### ISSUE THREAD

**Issue by sawa-ko** [mololab/json-translator#19]
![image](https://user-images.githubusercontent.com/56084970/214436210-89e14cac-37bb-430a-992d-0ac41381fbce.png)

Error: Too many request!

**Comment by ParvinEyvazov** [comment]
Hi @kaname-png 

Unfortunately, Libre's and Argos' Free APIs are now responding "Too Many Requests" errors after sending only a couple of requests. 

Also mentioned here: https://github.com/mololab/json-translator/issues/18

I will try to find a way of using it.

Please, for now, use Bing Microsoft Translate or Google Translate.
