### ISSUE TITLE
Debugging with VSCODE

### ISSUE THREAD

**Issue by edelciomolina** [mololab/json-translator#21]
I'm trying to use json-translator with a JSON that shows that the process is done, but without any translations. So, I hope to get help with debugging, but I don't have experience with this kind of structure to run and debug the CLI.

Can anyone help me with a launch.json to run TypeScript watch while running it in VS Code for debugging?

**Comment by ParvinEyvazov** [comment]
Hey @edelciomolina  apologies, completely missed your issue 😲.

Unfortunately, debugging is always a headache on CLI.

There are some helpful commands on makefile to build and run cli on your local machine with using `npm link`.

- [windows](https://github.com/mololab/json-translator/blob/master/makefile#L18)
- [mac](https://github.com/mololab/json-translator/blob/master/makefile#L25)

You can run these make commands (for ex: `make run-cli-mac`) and that will build and link cli. Now you are running the cli from your local machine.
