### ISSUE TITLE
Setup my own LibreTranslate instance

### ISSUE THREAD

**Issue by Monkey-Island** [mololab/json-translator#24]
Hi,

With Google and Bing, there are a lot of limitations and it's too slow. To avoid network issues with Libre Translate, is there an option to setup the IP/port of my own Libre Translate?

Best Regards,
LeChuck

**Comment by ParvinEyvazov** [comment]
Hi @Monkey-Island ,

There is not an option for doing it for not, but that would be a great improvement for a package.

I would like to implement it soon.

Thank you.
