### ISSUE TITLE
302 moved permanetly

### ISSUE THREAD

**Issue by shashika18923** [mololab/json-translator#27]
When I translating json object its not translating in cmd its showing for request body302 moved permanently and bad request

**Comment by ParvinEyvazov** [comment]
Hi @shashika18923 ,

which source are you using from the list below?
- Libre
- Argos
- Google
- Bing

That should be a temporary error from the service.

**Comment by israel-kochava** [comment]
I too saw this with 1.6.3 and posted yesterday a note [here](https://github.com/mololab/json-translator/issues/31).  it is not resolved, for me at least, as you can see.  And 1.6.4 results in the "--" errors.

**Comment by ParvinEyvazov** [comment]
@israel-kochava hi,

please check the comment[ here ](https://github.com/mololab/json-translator/issues/31#issuecomment-1867549531)

[more info in readme](https://github.com/mololab/json-translator?tab=readme-ov-file#options)
