### ISSUE TITLE
Add cli options for specify in/out language

### ISSUE THREAD

**Issue by Demetri0** [mololab/json-translator#28]
Wow! I'm really excited by this tool! It is amazing!

What do you think of idea to add more cli options like:
- `--from-lang=en` - to specify current language 
- `--target-langs=fr,cn` - to specify target languages
- `--translator=google` - to specify translation service

**Comment by ParvinEyvazov** [comment]
Hey @Demetri0, thank you for your feature suggestion ✌️

That sounds a great idea to help run CLI faster. Adding it to the feature list ✔️ to implement as soon as I will have time.

**Comment by FathiGuemri** [comment]
hello @Demetri0 @ParvinEyvazov 
#### The proposal has been implemented. Pending the pull request review #30

**Comment by ParvinEyvazov** [comment]
This feature is added in v1.7.0. ([v1.8.0](https://mololab.org/jsontt/npm) is out there now)

Huge thanks to @FathiGuemri 💛
