### ISSUE TITLE
At some point it just gives up?

### ISSUE THREAD

**Issue by psarno** [mololab/json-translator#32]
It outputted JSON files for my 8,000+ translations, but they are impartial.

English as input, French and Spanish as output.

For the French one, at one point, it stopped translating and everything thereafter is simply "--".

Note all the proper translations at the top, and then nothing for the rest of it:

![image](https://github.com/mololab/json-translator/assets/18640860/dcb1bbed-d557-43ed-82c8-bf0873cb14d4)

It said it completed it though.

![image](https://github.com/mololab/json-translator/assets/18640860/3d5e8150-d09b-440e-a019-9945c1a860a6)

For the Spanish one, the entire file is all just "--".   Zero translations.

![image](https://github.com/mololab/json-translator/assets/18640860/ec4273d6-0c2c-419e-a92c-13f59b4d3b5c)

**Comment by kuxonline** [comment]
I have the same problem. First time when i installed worked like a charm. Second time just -- Deinstalled and again installed but no difference. Maybe proxy is an issue but we must wait :)

**Comment by ParvinEyvazov** [comment]
@kuxonline @psarno @modestinoandre

Can you please try new version of jsontt([v1.8.0](https://mololab.org/jsontt/npm))?

**Comment by kuxonline** [comment]
@ParvinEyvazov works like a charm ;-)

**Comment by psarno** [comment]
Same result with 1.8.0 Google

Translate a few thne gives up.

![image](https://github.com/mololab/json-translator/assets/18640860/7c66eb26-ebc9-43a6-99a0-1c41a0e420dc)

**Comment by ParvinEyvazov** [comment]
@psarno @kuxonline 
now `jsontt v.2.0.0` supports fallback logic which tries another translation service on fail instead of assigning "--".

But if all services fail, it will assign "--".

[More info in readme](https://github.com/mololab/json-translator?tab=readme-ov-file#options)
