### ISSUE TITLE
Tatar is not available

### ISSUE THREAD

**Issue by Animushka** [mololab/json-translator#33]
jsontt ru.json --translator bing --from ru --to tt

 [tt]: the Languages to translate into is not available

supported Languages: https://github.com/mololab/json-translator/blob/master/docs/LANGUAGES.md
<img width="654" alt="image" src="https://github.com/mololab/json-translator/assets/71054551/3d813652-23e4-435c-9aee-9e557266a15c">

**Comment by ParvinEyvazov** [comment]
This is a bug. Bing should support Tatar language. I will try to solve it soon.

**Comment by ParvinEyvazov** [comment]
Hi @Animushka ,

Issue is fixed on new version [v1.8.0](https://github.com/mololab/json-translator/releases/tag/1.8.0)
