### ISSUE TITLE
Set API Key

### ISSUE THREAD

**Issue by jclimac** [mololab/json-translator#34]
Is it possible to set an API Key for Google instead of using its free endpoint?

**Comment by ParvinEyvazov** [comment]
Hello @jclimac 

Main purpose was to keep the whole operation free.

Currently `jsontt` does not support working with API Key. But I guess that would be good feature who already has an API Key.

Also there are some projects who already doing it [like this](https://github.com/KhaledMohamedP/translate-json-object)

**Comment by ParvinEyvazov** [comment]
Hi @jclimac 

FYI: I have a plan to add new Translation modules with setting their keys. (Like Google Translate with API key, GPT with openAI keys, DeepL with API key, etc.)
