### ISSUE TITLE
Steps For jsontt CLI

### ISSUE THREAD

**Issue by Gopal-Swami** [mololab/json-translator#4]
@ParvinEyvazov ,

Could you please tell how to create jsontt CLI to use ?

**Comment by ParvinEyvazov** [comment]
Hi, you should install it as globally(```-g```).
Here is the command you can do:

 ```npm i -g @parvineyvazov/json-translator```

Great feedback, I am updating the README file to make it more clear. Thank you @Gopal-Swami .

**Comment by Gopal-Swami** [comment]
Thanks @ParvinEyvazov , It worked.
