### ISSUE TITLE
Feature Request: Skip Empty Strings in Translation to Avoid Unnecessary Errors

### ISSUE THREAD

**Issue by tomasen** [mololab/json-translator#59]
I found that trying to translate empty strings leads to unnecessary processing and error handling.

```
error while translating "" using google2. Assigned "--" instead of exit from cli.
```

Proposed Solution

I propose that the translation feature be enhanced to automatically skip empty strings and apply the output as is. This approach would prevent the system from attempting to translate an empty input, thereby avoiding the generation of errors and improving efficiency.

Expected Outcome

Implementing this feature can:

	•	Reducing unnecessary error messages that clutter the system logs.
	•	Saving computational resources by not processing empty inputs.
	•	Simplifying error handling in scripts and applications that utilize this translation feature.

**Comment by ParvinEyvazov** [comment]
Fixed on release jsontt v2.2.4

Thank you @tomasen
