### ISSUE TITLE
'jsontt' is not recognized

### ISSUE THREAD

**Issue by merolaika** [mololab/json-translator#6]
Hello sir, i get this error

jsontt /files/en.json
'jsontt' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ParvinEyvazov** [comment]
Hi @merolaika ,

Can you please try to install it globally with this command and run it after that:

`npm i -g @parvineyvazov/json-translator`

**Comment by merolaika** [comment]
Hello again sir, yes i do but again same problem how can i fix this sir? 

D:\python\yenii\json-translator>npm i -g @parvineyvazov/json-translator

changed 91 packages, and audited 92 packages in 8s

10 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

D:\python\yenii\json-translator>jsontt /files/en.json
'jsontt' is not recognized as an internal or external command,
operable program or batch file.

**Comment by merolaika** [comment]
PS D:\python\yenii\json-translator> jsontt
jsontt : The term 'jsontt' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is cor
rect and try again.
At line:1 char:1
+ jsontt
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (jsontt:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ParvinEyvazov** [comment]
Can you please provide the version of npm and node?

For npm(not %100 sure that will work on windows) `npm version`
For node: `node -v`

**Comment by merolaika** [comment]
Hello sir;

D:\python\yenii\json-translator>npm version
{
  '@parvineyvazov/json-translator': '1.1.0',
  npm: '8.19.2',
  node: '16.13.2',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}


um so let me download it on linux thanks for answer sir

**Comment by ParvinEyvazov** [comment]
Can you try to install it this way:

`npm install --location=global @parvineyvazov/json-translator`

**Comment by ParvinEyvazov** [comment]
If it didn't work, the last thing you can do is to add an env path.

Steps:
1 - find where are npm packages
`npm get prefix`

2 - Copy this path

3 - Add this path as env path
`set PATH=%PATH%;C:\your\path\here\`

For example in my case, npm packages are under `C:\Program Files\nodejs` (result of Step 1)
I have to run `set PATH=%PATH%;C:\Program Files\nodejs\` (*dont forget to add backslash"\\" to end*)

**Comment by merolaika** [comment]
> If it didn't work, the last thing you can do is to add an env path.
> 
> Steps: 1 - find where are npm packages `npm get prefix`
> 
> 2 - Copy this path
> 
> 3 - Add this path as env path `set PATH=%PATH%;C:\your\path\here\`
> 
> For example in my case, npm packages are under `C:\Program Files\nodejs` (result of Step 1) I have to run `set PATH=%PATH%;C:\Program Files\nodejs\` (_dont forget to add backslash"\" to end_)

Thanks for help sir,, this working for me

**Comment by ParvinEyvazov** [comment]
Awesome 🥳️. I will update the README about this regarding anyone will not face the same kind of problem.
