### ISSUE TITLE
How to set api key using CLI on Windows ?

### ISSUE THREAD

**Issue by yunuselci** [mololab/json-translator#63]
The question is on title, how can i set api key using CLI on Windows ?

**Comment by ParvinEyvazov** [comment]
Hi @yunuselci, this is actually not fully related to jsontt.

But for help:
It should be smth like:

`set OPENAI_API_KEY=your-key-here`

jsontt using the keys from Environment Variables. That is why you need to figure out how you can set your key on your environments.

For more info, you can google smth like: `how to set environment variables in Windows`
