### ISSUE TITLE
Feature request : Add support for Openrouter, cohere, anthropic ,together, llamacpp and Google Gemini Api

### ISSUE THREAD

**Issue by tukangcode** [mololab/json-translator#65]
Hello and how are you.
in future development can you add

1.  Openrouter, 
2. cohere, 
3. anthropic 
4. ,together ai, 
5. llamacpp and 
6. Google Gemini Api
 as part of engine and module for translation ?
thanks.

**Comment by ParvinEyvazov** [comment]
hi @tukangcode, sounds fantastic! I am adding them to roadmap.
