### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by tukangcode** [mololab/json-translator#66]
Hi again, can you added instalation guide ? i try follow your guide but not working. maybe video will help. thanks.

**Comment by tukangcode** [comment]
never mind figure it out with chatgpt but now how i find half finish translate file ?

**Comment by ParvinEyvazov** [comment]
Hi @tukangcode, what exactly do you mean half finish translate file? jsontt only saves the file when translation is done

**Comment by tukangcode** [comment]
ah... Sorry I thought it keep half finish translation file, I use Google
Translate to translate 7k string and bit slow and because it late a night I
think getting half finish translation better than nothing
