### ISSUE TITLE
Error with OPENAI API

### ISSUE THREAD

**Issue by phederal** [mololab/json-translator#76]
error while translating "Looking" using gpt-3.5-turbo. Assigned "--" instead of exit from cli.
I installed the api user key and it still doesn't work. How to solve the problem? Is it possible to trace the cause?

**Comment by ParvinEyvazov** [comment]
Hi @phederal, did you set the api key?

**Comment by ParvinEyvazov** [comment]
I am closing this issue @phederal.

Please, feel free to open it back if the issue still happening
